user: kiubmenc
# optional, prompted if none given
password: Qv0l44c3r3qv0l4!
host: ftp.kiubmen.com
port: 21
client:
  localRoot: /build
  remoteRoot: /public_html/fountainyouth4u
  # this would upload everything except dot files
  include: ['*', '.*', '**/*']
  # e.g. exclude sourcemaps
  exclude:
    - 'build/**/*.map'
  # delete existing files at destination before uploading
  deleteRoot: true
